version: '3.1'

services:
  mongodb:
    image: mongo:latest
    ports:
     -  "27017:27017"
    command: ["mongod", "--noauth", "--bind_ip_all"]
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    
volumes:
  mongodb_data:
