version: '3.1'

services:
  web:
    build: .
    ports:
      - "6789:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vuln_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./vuln_db.sql:/docker-entrypoint-initdb.d/vuln_db.sql

volumes:
  dbdata:

